[package]
name = "WebPresence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrome_native_messaging = "0.3.0"
discord-rich-presence = "0.2.3"